# This is a basic workflow to help you get started with Actions

name: CD

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: 
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  convert_via_pandoc:
    runs-on: ubuntu-18.04
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
      - name: convert
        uses: docker://pandoc/core:2-ubuntu
        with:
          args: "-t gfm --extract-media=gitbook/Pictures docs/ServoDrive-SetupGuide_EP.odt -o gitbook/ServoDrive-SetupGuide_trial.md" # gets appended to pandoc command
      - name: List files in the repository (debug)
        run: |
          ls ${{ github.workspace }}
      - name: result
        uses: actions/upload-artifact@v3
        with:
          path: gitbook/ServoDrive-SetupGuide_trial.md
      - name: push to repo
        run: |
          git config --global user.name "sm"
          git config --global user.email "sergio.miracco@triamec.com"
          git add gitbook 
          git commit -m "generate gitbook from docs"
          git push
